apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: testconfigmaps.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
              properties:
                name:
                  type: string
            spec:
              type: object
              required:
              - data
              properties:
                data:
                  type: object
                  additionalProperties:
                    type: string
                    
  names:
    kind: TestConfigMap
    plural: testconfigmaps
    singular: testconfigmap
  scope: Namespaced
